JPFinancial/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using JPFData;
using JPFData.Managers;
using JPFData.Models.JPFinancial;
using JPFData.ViewModels;
using PagedList;

namespace JPFinancial.Controllers
{
    [Authorize]
    public class AccountsController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        private readonly AccountManager _accountManager = new AccountManager();

        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                // Prevents page from breaking due to error updating or rebalancing
                try
                {
                    //_accountManager.Update();
                    //_accountManager.Rebalance();
                }
                catch (Exception e)
                {
                    Logger.Instance.Error(e);
                }
                
                var accountVM = GetAccountVM(1);
              
             
                return View(accountVM);
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return View("Error: " + e);
            }
        }

        [HttpPost]
        public ActionResult Create(AccountViewModel accountVM)
        {
            try
            {

                if (!_accountManager.Create(accountVM.Account)) return View("Error");


                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return View("Error");
            }
        }

        [HttpPost]
        public JsonResult EditAccount(Account account)
        {
            try
            {
                return Json(_accountManager.Edit(account) ? "Success" : "Failed");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return Json("Error");
            }
        }

        [HttpPost]
        public JsonResult DeleteAccount(Account account)
        {
            try
            {
                //TODO: Add verification and notification of success 
                return account.Id > 0 ? Json(_accountManager.Delete(account.Id) ? "Success" : "Failed") : Json("ID is invalid");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return Json("Error: " + e);
            }
        }

        [HttpPost]
        public JsonResult UpdateAccounts(List<Account> accounts)
        {
            try
            {
                return accounts.Count > 0
                    ? Json(_accountManager.UpdateAccountsFromDashboard(accounts) ? "Success" : "Failed") : Json("No Accounts received");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return Json("Error: " + e);
            }
        }

        [HttpGet]
        public ActionResult PageAccounts(int page = 1)
        {
            try
            {

                var accountVM = GetAccountVM(page);               
           

                return PartialView("_AccountsTable", accountVM);
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return View("Error");
            }
        }

        private AccountViewModel GetAccountVM(int page)
        {
            var pageSize = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["defaultPageSize"]);

            var accountVM = new AccountViewModel();
            accountVM.Accounts = _accountManager.GetAllAccountsForTransactions().OrderByDescending(a => a.Balance).ThenBy(a => a.Name).ToList();
            accountVM.PagedAccounts = accountVM.Accounts.ToPagedList(page, pageSize);


            return accountVM;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JPFinancial/Controllers/BillsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using JPFData;
using JPFData.Enumerations;
using JPFData.Managers;
using JPFData.Models.JPFinancial;
using JPFData.ViewModels;
using PagedList;

namespace JPFinancial.Controllers
{
    [Authorize]
    public class BillsController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        private readonly BillManager _billManager = new BillManager();
        private readonly ExpenseManager _expenseManager = new ExpenseManager();
        private readonly AccountManager _accountManager = new AccountManager();
        private readonly TransactionManager _transactionManager = new TransactionManager();

        [HttpGet]       
        public ActionResult Index()
        {

            var billVM = GetBillVM(1);


            return View(billVM);
        }

        [HttpPost]
        public JsonResult Create(BillWithAccount vm)
        {
            try
            {
                if (vm.FrequencyId > 0) vm.Frequency = (FrequencyEnum)vm.FrequencyId;


                var bill = MapToBill(vm);
                if (vm.AccountId != 0) return Json(!_billManager.Create(bill) ? "Error" : "Success");


                var account = MapToAccount(vm);
                _accountManager.Create(account);
                bill.AccountId = account.Id;

                return Json(!_billManager.Create(bill) ? "Error" : "Success");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return Json("Error");
            }
        }

        [HttpPost]
        public JsonResult EditBill(Bill bill)
        {
            try
            {
                return Json(_billManager.Edit(bill) ? "Success" : "Failed");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return Json("Error");
            }
        }

        [HttpPost]
        public JsonResult DeleteBill(Bill bill)
        {
            try
            {
                return bill.Id > 0 ? Json(_billManager.Delete(bill.Id) ? "Success" : "Failed") : Json("ID is invalid");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return Json("Error");
            }
        }

        [HttpPost]
        public JsonResult SetExpenseToPaid(Expense expense)
        {
            try
            {
                if (expense.Id >= 1)
                    return _expenseManager.SetExpenseToPaid(expense.Id) ? Json("Success") : Json("Failed");


                Logger.Instance.Info("Invalid Expense Id");
                return Json("Invalid Expense Id");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return Json("Error");
            }
        }

        [HttpPost]
        public JsonResult SetExpenseToPaidWithTransaction(Expense expense)
        {
            try
            {
                if (expense.Id < 1)
                {
                    Logger.Instance.Info("Invalid Expense Id");
                    return Json("Invalid Expense Id");
                }

                if (expense.CreditAccountId < 1)
                {
                    Logger.Instance.Info("Invalid Credit Account Id");
                    return Json("Invalid Credit Account Id");
                }

                var transactionVM = new TransactionViewModel();

                var transaction = new Transaction();
                transaction.Type = TransactionTypesEnum.Expense;
                transaction.Category = CategoriesEnum.ManualPayment;
                transaction.Amount = expense.Amount;
                transaction.CreditAccountId = expense.CreditAccountId;
                transaction.SelectedExpenseId = expense.Id;
                transaction.Date = expense.Due;
                transaction.Payee = "Manual Expense Payment";

                transactionVM.Transaction = transaction;


                return _transactionManager.Create(transactionVM) ? Json("Success") : Json("Failed");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return Json("Error");
            }
        }

        [HttpGet]
        public ActionResult PageExpenses(int page = 1)
        {

            var billVM = GetBillVM(page);


            return PartialView("_ExpensesTable", billVM.PagedExpenses);
        }

        [HttpGet]
        public ActionResult PageBills(int page = 1)
        {
            
            var billVM = GetBillVM(page);


            return PartialView("_BillsTable", billVM);
        }

        private BillViewModel GetBillVM (int page = 1)
        {

            var pageSize = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["defaultPageSize"]);

            BillViewModel billVM = new BillViewModel();
            billVM.Accounts = _accountManager.GetAllAccounts();
            billVM.Bills = _billManager.GetAllBills().OrderBy(b => b.DueDate).ThenBy(b => b.Name).ToList();
            billVM.PagedBills = billVM.Bills.ToPagedList(page, pageSize);
            billVM.Expenses = _expenseManager.GetAllUnpaidExpenses().OrderBy(e => e.Due).ThenBy(e => e.Name).ToList();
            billVM.Metrics = _billManager.GetBillMetrics();
            billVM.PagedExpenses = billVM.Expenses.ToPagedList(page, pageSize);


            return billVM;
        }

        private Bill MapToBill(BillWithAccount vm)
        {
            var bill = new Bill();

            bill.Name = vm.Name;
            bill.AmountDue = vm.AmountDue;
            bill.PaymentFrequency = vm.Frequency;
            bill.DueDate = vm.DueDate;
            if (vm.AccountId != null) bill.AccountId = (int) vm.AccountId;


            return bill;
        }

        private Account MapToAccount(BillWithAccount vm)
        {
            var account = new Account();

            account.Name = vm.AccountName;
            account.Balance = vm.AccountBalance;
            account.PaycheckContribution = vm.AccountPaycheckContribution;


            return account;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

    public class BillWithAccount
    {
        public string Name { get; set; }
        public decimal AmountDue { get; set; }
        public DateTime DueDate { get; set; }
        public int? FrequencyId { get; set; }
        public FrequencyEnum Frequency { get; set; }
        public int? AccountId { get; set; }
        public string AccountName { get; set; }
        public decimal AccountBalance { get; set; }
        public decimal AccountPaycheckContribution { get; set; }
    }
}

JPFinancial/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JPFinancial.Controllers
{
    public class SupportController : Controller
    {
        // GET: Support
        public ActionResult GettingStarted()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

JPFinancial/Controllers/TransactionsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using JPFData;
using JPFData.Enumerations;
using JPFData.Managers;
using JPFData.Models.JPFinancial;
using JPFData.ViewModels;
using PagedList;

namespace JPFinancial.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        private readonly TransactionManager _transactionManager = new TransactionManager();

        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                var transactionVM = GetTransactionVM(1);


                return View(transactionVM);
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult Create(TransactionViewModel transactionVM)
        {
            try
            {
                switch (transactionVM.Type)
                {
                    case TransactionTypesEnum.Expense:
                        {
                            if (transactionVM.IsBill)
                            {
                                ExpenseManager expenseManager = new ExpenseManager();
                                transactionVM.Transaction.Payee = expenseManager.GetExpense(transactionVM.Transaction?.SelectedExpenseId).Name ??
                                    string.Empty;
                                ModelState["Transaction.Payee"].Errors.Clear();
                                UpdateModel(transactionVM.Transaction);
                            }
                            else
                            {
                                UpdateModel(transactionVM.Transaction);
                            }


                            if (!ModelState.IsValid) return View("Error");
                            if (!_transactionManager.Create(transactionVM)) return View("Error");
                            break;
                        }
                    case TransactionTypesEnum.Income:
                        {
                            if (!transactionVM.AutoTransferPaycheckContributions)
                                _transactionManager.Create(transactionVM);
                            else
                            {
                                if (!_transactionManager.HandlePaycheckContributions(transactionVM.Transaction))
                                    return View("Error");
                            }

                            break;
                        }
                    //case TransactionTypesEnum.Transfer:
                    //    throw new NotImplementedException();
                    default:
                        throw new NotImplementedException();
                }
                

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return View("Error");
            }
        }

        [HttpPost]
        public JsonResult EditTransaction(Transaction transaction)
        {
            try
            {
                return Json(_transactionManager.Edit(transaction) ? "Success" : "Failed");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return Json("Error");
            }
        }

        [HttpPost]
        public JsonResult DeleteTransaction(Transaction transaction)
        {
            try
            {
                return transaction.Id > 0
                    ? Json(_transactionManager.Delete(transaction.Id) ? "Success" : "Failed")
                    : Json("ID is invalid");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return Json("Error");
            }
        }

        [HttpGet]
        public ActionResult PageTransactions(int page = 1)
        {
            try
            {
                var transactionVM = GetTransactionVM(page);


                return PartialView("_TransactionsTable", transactionVM);
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return View("Error");
            }
        }

        private TransactionViewModel GetTransactionVM(int page)
        {
            var pageSize = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["defaultPageSize"]);

            var transactionVM = new TransactionViewModel();
            transactionVM.Transactions = _transactionManager.GetAllTransactions().OrderByDescending(t => t.Date).ThenBy(t => t.Amount);
            transactionVM.PagedTransactions = transactionVM.Transactions.ToPagedList(page, pageSize);
            transactionVM.Metrics = _transactionManager.GetMetrics();


            return transactionVM;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JPFinancial/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Info";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

JPFinancial/Views/Shared/_AccountsTable.cshtml
@using PagedList.Mvc
@model JPFData.ViewModels.AccountViewModel


<table class="table table-striped table-dark" id="accountsTable">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Name</th>
            <th scope="col">Balance</th>
            <th scope="col">Required Savings</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row" class="addButtonColumn"><button class="addButton" type="submit" name="submitButton" value="Add"><i class="fa fa-plus-circle addIcon"></i></button></th>
            <td>
                @Html.EditorFor(model => model.Account.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Account.Name, "", new { @class = "text-danger" })
            </td>
            <td>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">$</span>
                    </div>
                    @Html.EditorFor(model => model.Account.Balance, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Account.Balance, "", new { @class = "text-danger" })
                </div>
            </td>
            <td></td>
        </tr>
        @if (Model != null && Model.PagedAccounts.Count > 0)
        {
            foreach (var item in Model.PagedAccounts)
            {
                var rowId = "rowId_" + item.Id;

                var nameId = "accountName_" + item.Id;
                var balanceId = "accountBalance_" + item.Id;
                var requiredSavingsId = "accountRequiredSavings_" + item.Id;
                <tr class="tableRow" id="@rowId">
                    <th scope="row"></th>
                    <td id="@nameId">@item.Name</td>
                    <td id="@balanceId">@item.Balance.ToString("C")</td>
                    <td id="@requiredSavingsId">@item.RequiredSavings.ToString("C")</td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="4">No Accounts</td>
            </tr>
        }
    </tbody>
    <tfoot>
        @if (Model != null && Model.PagedAccounts.Count != 0)
        {
            <tr>
                <td colspan="4">
                    <div class="fixed-table-pagination" style="display: block;">
                        <div class="pull-left">
                            @Html.PagedListPager(Model.PagedAccounts,
                                                page => Url.Action("PageAccounts", "Accounts", new
                                                {
                                                    page,
                                                    pageSize = Model.PagedAccounts.PageSize,
                                                    TotalItemCount = Model.PagedAccounts.TotalItemCount,
                                                    CurrentPage = Model.PagedAccounts.PageNumber,
                                                    sortOrder = "",
                                                    fieldName = "",
                                                    IsShowControls = false,
                                                    IsShowFirstLast = false,
                                                    IsShowPages = true
                                                }),
                                                PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                                                    new PagedListRenderOptions(),
                                                    new AjaxOptions()
                                                    {
                                                        HttpMethod = "GET",
                                                        UpdateTargetId = "accountsTable",
                                                        OnComplete = "addTableListeners"
                                                    }))
                        </div>
                        <div class="pull-right pagination-detail header-title pd-tp-bt-10">
                            <span class="pagination pagination-info">
                                Page @(Model.PagedAccounts.PageCount < Model.PagedAccounts.PageNumber ? 0 : Model.PagedAccounts.PageNumber) of @Model.PagedAccounts.PageCount
                                /
                                @(Model.PagedAccounts.TotalItemCount) items in @(Model.PagedAccounts.PageCount) pages
                            </span>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tfoot>
</table>

JPFinancial/Views/Shared/_BillsTable.cshtml
@using PagedList.Mvc
@model JPFData.ViewModels.BillViewModel


<table class="table table-striped table-dark" id="billsTable">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Name</th>
            <th scope="col">Amount Due</th>
            <th scope="col">Due Date</th>
            <th scope="col">Frequency</th>
            <th scope="col">Linked Account</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row" class="addButtonColumn"><button class="addButton" id="addButton" value="Add"><i class="fa fa-plus-circle addIcon"></i></button></th>
            <td>
                @Html.EditorFor(model => model.Bill.Name, new { htmlAttributes = new { @class = "form-control", @id="newBillName" } })
                @Html.ValidationMessageFor(model => model.Bill.Name, "", new { @class = "text-danger" })
            </td>
            <td>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">$</span>
                    </div>
                    @Html.EditorFor(model => model.Bill.AmountDue, new { htmlAttributes = new { @class = "form-control", @id="newBillAmountDue" } })
                    @Html.ValidationMessageFor(model => model.Bill.AmountDue, "", new { @class = "text-danger" })
                </div>
            </td>
            <td>
                @Html.EditorFor(model => model.Bill.DueDate, new { htmlAttributes = new { @class = "form-control", @id="newBillDueDate" } })
                @Html.ValidationMessageFor(model => model.Bill.DueDate, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.EnumDropDownListFor(model => model.Bill.PaymentFrequency, "Payment Frequency", htmlAttributes: new { @class = "form-control", @onchange = "setHiddenForFrequency(event)", @id="newBillFrequencyId" })
                @Html.ValidationMessageFor(model => model.Bill.PaymentFrequency, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.DropDownListFor(model => model.Bill.AccountId, new SelectList(Model.Accounts, "Id", "Name"), "--Select Account--", htmlAttributes: new { @class = "form-control", @onchange = "setHiddenForAccount(event)", @id = "newBillAccountId" })
                @Html.ValidationMessageFor(model => model.Bill.AccountId, "", new { @class = "text-danger" })
            </td>
        </tr>
        @if (Model.PagedBills != null && Model.PagedBills.Count > 0)
            {
                foreach (var item in Model.PagedBills)
                {
                    var rowId = "rowId_" + item.Id;
                    var nameId = "billName_" + item.Id;
                    var amountDueId = "billAmountDue_" + item.Id;
                    var dueDateId = "billDueDate_" + item.Id;
                    var frequencyNameId = "billFrequency_" + item.Id;
                    var frequencyId = "billFrequencyId_" + item.Id;
                    var accountNameId = "billAccount_" + item.Id;
                    var accountId = "billAccountId_" + item.Id;
                    var frequencyIdValue = (int)item.PaymentFrequency;
                    var accountIdValue = item.AccountId;
                <tr class="tableRow" id="@rowId">
                    <th scope="row"></th>
                    <td id="@nameId">@item.Name</td>
                    <td id="@amountDueId">@item.AmountDue.ToString("C")</td>
                    <td id="@dueDateId">@item.DueDate.ToShortDateString()</td>
                    <td id="@frequencyNameId">@item.PaymentFrequency</td>
                    @if (@item.Account != null)
                    {
                        <td id="@accountNameId">@item.Account.Name</td>
                    }
                    else
                    {
                        <td id="@accountNameId"></td>
                    }
                    <td id="@frequencyId" style="display: none">@frequencyIdValue</td>
                    <td id="@accountId" style="display: none">@accountIdValue</td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="6">No Bills</td>
            </tr>
        }
    </tbody>
    @if (Model.PagedBills != null && Model.PagedBills.Count != 0)
            {
        <tr>
            <td colspan="6">
                <div class="fixed-table-pagination" style="display: block;">
                    <div class="pull-left">
                        @Html.PagedListPager(Model.PagedBills,
                                                    page => Url.Action("PageBills", "Bills", new
                                                    {
                                                        page,
                                                        pageSize = Model.PagedBills.PageSize,
                                                        CurrentPage = Model.PagedBills.PageNumber,
                                                        sortOrder = "",
                                                        fieldName = "",
                                                        IsShowControls = false,
                                                        IsShowFirstLast = false,
                                                        IsShowPages = true
                                                    }),
                            PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                                new PagedListRenderOptions(),
                                new AjaxOptions
                                {
                                    HttpMethod = "GET",
                                    UpdateTargetId = "billsTable",
                                    OnComplete = "addTableListeners"
                                }))
                    </div>
                    <div class="pull-right pagination-detail header-title pd-tp-bt-10">
                        <span class="pagination pagination-info">
                            Page @(Model.PagedBills.PageCount < Model.PagedBills.PageNumber ? 0 : Model.PagedBills.PageNumber) of @Model.PagedBills.PageCount
                            /
                            @(Model.PagedBills.TotalItemCount) items in @(Model.PagedBills.PageCount) pages
                        </span>
                    </div>
                </div>
            </td>
        </tr>
    }
</table>

JPFinancial/Views/Shared/_ExpensesTable.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<JPFData.Models.JPFinancial.Expense>



<table class="table table-striped table-dark" id="expensesTable">
    <thead>
        <tr class="header">
            <th scope="col">Expense</th>
            <th scope="col">Amount Due</th>
            <th scope="col">Due Date</th>
            <th scope="col"></th>
        </tr>
    </thead>
    @if (Model != null && Model.Count > 0)
    {
        <tbody>
            @foreach (var item in Model)
            {
                var expenseId = "expenseId_" + item.Id;
                var nameId = "expenseName_" + item.Id;
                var amountDueId = "expenseAmountDue_" + item.Id;
                var dueDateId = "expenseDueDate_" + item.Id;
                var creditAccountId = "expenseCreditAccountId_" + item.Id;

                @Html.Hidden(@creditAccountId, item.CreditAccountId);

                <tr>
                    <td id="@nameId">@item.Name</td>
                    <td id="@amountDueId">@item.Amount.ToString("C")</td>
                    <td id="@dueDateId">@item.Due.ToShortDateString()</td>
                    <td><button id="@expenseId" class="payBillButtons btn btn-dark btn-sm">Mark as Paid</button></td>
                </tr>
            }
        </tbody>
    }
    else
    {
        <tbody>
            <tr>
                <td colspan="4">No Unpaid Expenses</td>
            </tr>
        </tbody>
    }
    <tfoot>
        @if (Model != null && Model.Count != 0)
        {
            <tr>
                <td colspan="4">
                    <div class="fixed-table-pagination" style="display: block;">
                        <div class="pull-left">
                            @Html.PagedListPager(Model,
                                                    page => Url.Action("PageExpenses", "Bills", new
                                                    {
                                                        page,
                                                        pageSize = Model.PageSize,
                                                        CurrentPage = Model.PageNumber,
                                                        sortOrder = "",
                                                        fieldName = "",
                                                        IsShowControls = false,
                                                        IsShowFirstLast = false,
                                                        IsShowPages = true
                                                    }),
                                PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                                    new PagedListRenderOptions(),
                                    new AjaxOptions()
                                    {
                                        HttpMethod = "GET",
                                        UpdateTargetId = "expensesTable",
                                        OnComplete = "addTableListeners"
                                    }))
                        </div>
                        <div class="pull-right pagination-detail header-title pd-tp-bt-10">
                            <span class="pagination pagination-info">
                                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                                /
                                @(Model.TotalItemCount) items in @(Model.PageCount) pages
                            </span>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tfoot>
</table>


<div class="row">
    <div class="col-md-12" id="payExpenseDiv"></div>
</div>