JPFinancial/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using JPFData;
using JPFData.Managers;
using JPFData.Models.JPFinancial;
using JPFData.ViewModels;

namespace JPFinancial.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        private readonly AccountManager _accountManager = new AccountManager();
        private readonly DashboardManager _dashboardManager = new DashboardManager();


        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                DashboardViewModel dashboardVM = new DashboardViewModel();
                dashboardVM.Accounts = _accountManager.GetAllAccounts();
                dashboardVM.Metrics = _dashboardManager.RefreshStaticMetrics();
                _accountManager.Update();
                _accountManager.Rebalance();


                return View(dashboardVM);
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return View("Error");
            }
        }

        private SortedTransactions SortTransactions(IEnumerable<Transaction> transactions, int yearsBack)
        {
            var date = DateTime.Today;
            var year = date.Year;
            var month = date.Month;

            var howFarBack = date.AddYears(-yearsBack);
            var previousYear = new DateTime(howFarBack.Year, 1, 1);
            var sortedTransactions = new SortedTransactions();

            var balancesByMonth = new Dictionary<string, decimal>();
            var balancesByQuarter = new Dictionary<string, decimal>();
            var balancesByYear = new Dictionary<string, decimal>();
            var balancesByType = new Dictionary<string, decimal>();
            var balancesByCategory = new Dictionary<string, decimal>();
            var previousYearBalancesByMonth = new Dictionary<string, decimal>();
            var previousYearBalancesByQuarter = new Dictionary<string, decimal>();
            var previousYearBalancesByYear = new Dictionary<string, decimal>();
            var previousYearBalancesByType = new Dictionary<string, decimal>();
            var previousYearBalancesByCategory = new Dictionary<string, decimal>();

            var yearBackTransactions = transactions.Where(t => t.Date > howFarBack);
            var lastYearTransactions = transactions.Where(t => t.Date >= previousYear && t.Date <= new DateTime(previousYear.Year, 12, 31));

            foreach (var transaction in yearBackTransactions)
            {
                var transactMonth = transaction.Date.Month;
                var transactYear = transaction.Date.Year;
                var monthKey = string.Concat(transactMonth.ToString(), transactYear);
                if (balancesByMonth.ContainsKey(monthKey))
                {
                    var currentBalance = balancesByMonth[$"{monthKey}"];
                    var newBalance = Convert.ToDecimal(transaction.Amount + currentBalance);
                    balancesByMonth[monthKey] = newBalance;
                }
                else
                {
                    balancesByMonth.Add(monthKey, Convert.ToDecimal(transaction.Amount));
                }
            }

            foreach (var transaction in lastYearTransactions)
            {
                var transactMonth = transaction.Date.Month;
                var transactYear = transaction.Date.Year;
                var monthKey = string.Concat(transactMonth.ToString(), transactYear);
                if (previousYearBalancesByMonth.ContainsKey(monthKey))
                {
                    var currentBalance = previousYearBalancesByMonth[$"{monthKey}"];
                    var newBalance = Convert.ToDecimal(transaction.Amount + currentBalance);
                    previousYearBalancesByMonth[monthKey] = newBalance;

                    switch (transactMonth)
                    {
                        case 1:
                        case 2:
                        case 3:
                            previousYearBalancesByQuarter[$"firstQuarter{transactYear}"] += Convert.ToDecimal(transaction.Amount);
                            break;
                        case 4:
                        case 5:
                        case 6:
                            previousYearBalancesByQuarter[$"secondQuarter{transactYear}"] += Convert.ToDecimal(transaction.Amount);
                            break;
                        case 7:
                        case 8:
                        case 9:
                            previousYearBalancesByQuarter[$"thirdQuarter{transactYear}"] += Convert.ToDecimal(transaction.Amount);
                            break;
                        case 10:
                        case 11:
                        case 12:
                            previousYearBalancesByQuarter[$"forthQuarter{transactYear}"] += Convert.ToDecimal(transaction.Amount);
                            break;
                    }
                }
                else
                {
                    previousYearBalancesByMonth.Add(monthKey, Convert.ToDecimal(transaction.Amount));

                    switch (transactMonth)
                    {
                        case 1:
                        case 2:
                        case 3:
                            previousYearBalancesByQuarter[$"firstQuarter{transactYear}"] = Convert.ToDecimal(transaction.Amount);
                            break;
                        case 4:
                        case 5:
                        case 6:
                            previousYearBalancesByQuarter[$"secondQuarter{transactYear}"] = Convert.ToDecimal(transaction.Amount);
                            break;
                        case 7:
                        case 8:
                        case 9:
                            previousYearBalancesByQuarter[$"thirdQuarter{transactYear}"] = Convert.ToDecimal(transaction.Amount);
                            break;
                        case 10:
                        case 11:
                        case 12:
                            previousYearBalancesByQuarter[$"forthQuarter{transactYear}"] = Convert.ToDecimal(transaction.Amount);
                            break;
                    }
                }
            }

            sortedTransactions.BalanceByMonth = balancesByMonth;
            sortedTransactions.LastYearBalanceByMonth = previousYearBalancesByMonth;
            sortedTransactions.BalanceByQuarter = balancesByQuarter;
            sortedTransactions.LastYearBalanceByQuarter = previousYearBalancesByQuarter;
            sortedTransactions.BalanceByYear = balancesByYear;
            sortedTransactions.LastYearBalanceByYear = previousYearBalancesByYear;
            sortedTransactions.BalanceByType = balancesByType;
            sortedTransactions.LastYearBalanceByType = previousYearBalancesByType;
            sortedTransactions.BalanceByCategory = balancesByCategory;
            sortedTransactions.LastYearBalanceByCategory = previousYearBalancesByCategory;

            return sortedTransactions;
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

    public class SortedTransactions
    {
        public Dictionary<string, decimal> BalanceByMonth { get; set; }
        public Dictionary<string, decimal> LastYearBalanceByMonth { get; set; }
        public Dictionary<string, decimal> BalanceByQuarter { get; set; }
        public Dictionary<string, decimal> LastYearBalanceByQuarter { get; set; }
        public Dictionary<string, decimal> BalanceByYear { get; set; }
        public Dictionary<string, decimal> LastYearBalanceByYear { get; set; }
        public Dictionary<string, decimal> BalanceByType { get; set; }
        public Dictionary<string, decimal> LastYearBalanceByType { get; set; }
        public Dictionary<string, decimal> BalanceByCategory { get; set; }
        public Dictionary<string, decimal> LastYearBalanceByCategory { get; set; }
    }
}

JPFinancial/Controllers/TransactionsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using JPFData;
using JPFData.Enumerations;
using JPFData.Managers;
using JPFData.Models.JPFinancial;
using JPFData.ViewModels;
using PagedList;

namespace JPFinancial.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        private readonly TransactionManager _transactionManager = new TransactionManager();

        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                var transactionVM = GetTransactionVM(1);


                return View(transactionVM);
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult Create(TransactionViewModel transactionVM)
        {
            try
            {
                switch (transactionVM.Type)
                {
                    case TransactionTypesEnum.Expense:
                        {
                            if (transactionVM.IsBill)
                            {
                                ExpenseManager expenseManager = new ExpenseManager();
                                transactionVM.Transaction.Payee = expenseManager.GetExpense(transactionVM.Transaction?.SelectedExpenseId).Name ??
                                    string.Empty;
                                ModelState["Transaction.Payee"].Errors.Clear();
                                UpdateModel(transactionVM.Transaction);
                            }
                            else
                            {
                                UpdateModel(transactionVM.Transaction);
                            }


                            if (!ModelState.IsValid) return View("Error");
                            if (!_transactionManager.Create(transactionVM)) return View("Error");
                            break;
                        }
                    case TransactionTypesEnum.Income:
                        {
                            if (!transactionVM.AutoTransferPaycheckContributions)
                                _transactionManager.Create(transactionVM);
                            else
                            {
                                if (!_transactionManager.HandlePaycheckContributions(transactionVM.Transaction))
                                    return View("Error");
                            }

                            break;
                        }
                    //case TransactionTypesEnum.Transfer:
                    //    throw new NotImplementedException();
                    default:
                        throw new NotImplementedException();
                }
                

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return View("Error");
            }
        }

        [HttpPost]
        public JsonResult EditTransaction(Transaction transaction)
        {
            try
            {
                return Json(_transactionManager.Edit(transaction) ? "Success" : "Failed");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return Json("Error");
            }
        }

        [HttpPost]
        public JsonResult DeleteTransaction(Transaction transaction)
        {
            try
            {
                return transaction.Id > 0
                    ? Json(_transactionManager.Delete(transaction.Id) ? "Success" : "Failed")
                    : Json("ID is invalid");
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return Json("Error");
            }
        }

        [HttpGet]
        public ActionResult PageTransactions(int page = 1)
        {
            try
            {
                var transactionVM = GetTransactionVM(page);


                return PartialView("_TransactionsTable", transactionVM);
            }
            catch (Exception e)
            {
                Logger.Instance.Error(e);
                return View("Error");
            }
        }

        private TransactionViewModel GetTransactionVM(int page)
        {
            var pageSize = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings["defaultPageSize"]);

            var transactionVM = new TransactionViewModel();
            transactionVM.Transactions = _transactionManager.GetAllTransactions().OrderByDescending(t => t.Date).ThenBy(t => t.Amount);
            transactionVM.PagedTransactions = transactionVM.Transactions.ToPagedList(page, pageSize);
            transactionVM.Metrics = _transactionManager.GetMetrics();


            return transactionVM;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JPFinancial/Views/Dashboard/Create.cshtml
@model JPFData.ViewModels.DashboardViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DashboardViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JPFinancial/Views/Dashboard/Delete.cshtml
@model JPFData.ViewModels.DashboardViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DashboardViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JPFinancial/Views/Dashboard/Details.cshtml
@model JPFData.ViewModels.DashboardViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DashboardViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>
</div>
<p>0
    @Html.ActionLink("Back to List", "Index")
</p>

JPFinancial/Views/Dashboard/Edit.cshtml
@model JPFData.ViewModels.DashboardViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>DashboardViewModel</h4>
        <hr />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JPFinancial/Views/Dashboard/IndexList.cshtml
@{
    ViewBag.Title = "IndexList";
}

<h2>IndexList</h2>

<div class="col-lg-6">
    <table class="table table-condensed table-bordered">
        <tr>
            <th>
            </th>
        </tr>

        @*@foreach (var account in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => account)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => )
                </td>
            </tr>
        }*@

    </table>
</div>

JPFinancial/Views/Dashboard/_AccountsPartial.cshtml
@model IEnumerable<JPFData.Models.JPFinancial.Account>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Balance)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Balance)
        </td>
    </tr>
}
</table>

JPFinancial/Views/Dashboard/_TopTransactions.cshtml
@model IEnumerable<JPFData.Models.JPFinancial.Transaction>

<h4 style="text-align: left; float: left; margin: 0; vertical-align: bottom">Most Expensive Transactions (Past 30 Days)</h4>
<h4 style="text-align: right; float: right; margin: 0; vertical-align: bottom">@Html.ActionLink("All Transactions", "Index", "Transactions")</h4>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Payee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Payee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td></td>
        </tr>
    }
</table>
<h4 class="col-md-12" style="-moz-align-content: center; -o-align-content: center; -webkit-align-content: center; align-content: center; margin: 12px 0 0 24px">@Html.ActionLink("All Transactions", "Index", "Transactions")</h4>